#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-numpy_ringbuffer
Version  : 0.2.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/93/8e/01693737a7a1b955137b8e45e40fedf155f031f5f824220a6a6ce887baea/numpy_ringbuffer-0.2.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/93/8e/01693737a7a1b955137b8e45e40fedf155f031f5f824220a6a6ce887baea/numpy_ringbuffer-0.2.1.tar.gz
Summary  : Ring buffer implementation for numpy
Group    : Development/Tools
License  : MIT
Requires: pypi-numpy_ringbuffer-python = %{version}-%{release}
Requires: pypi-numpy_ringbuffer-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(numpy)

%description
=================

        

        |Build Status| |codecov|

%package python
Summary: python components for the pypi-numpy_ringbuffer package.
Group: Default
Requires: pypi-numpy_ringbuffer-python3 = %{version}-%{release}

%description python
python components for the pypi-numpy_ringbuffer package.


%package python3
Summary: python3 components for the pypi-numpy_ringbuffer package.
Group: Default
Requires: python3-core
Provides: pypi(numpy_ringbuffer)
Requires: pypi(numpy)

%description python3
python3 components for the pypi-numpy_ringbuffer package.


%prep
%setup -q -n numpy_ringbuffer-0.2.1
cd %{_builddir}/numpy_ringbuffer-0.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641668792
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
